id = "io.buildpacks.stacks.ubi8"
homepage = "https://github.com/paketo-community/ubi-base-stack"
maintainer = "Paketo Community"

platforms = ["linux/amd64"]

[build]
  description = "base build ubi8 image to support buildpacks"
  dockerfile = "./build.Dockerfile"
  gid = 1000
  shell = "/bin/bash"
  uid = 1002

  [build.args]

[run]
  description = "base run ubi8 image to support buildpacks"
  dockerfile = "./run.Dockerfile"
  gid = 1000
  shell = "/bin/bash"
  uid = 1001

  [run.args]
